name: CI-CD
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Autenticando no Docker
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        uses: docker/login-action@v2.0.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          username:  ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
          
      - name: Criando e enviando imagens Docker ao hub
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./iac/kube-news/src/Dockerfile
          context: ./iac/kube-news/src
          push: true
          tags: |
            hernanisoares/kube-news:latest
            hernanisoares/kube-news:${{github.run_number}}
            
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3
      
      - name: Setando contexto Kubernetes
        uses: Azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}
          
      - name: Fazendo Deploy no cluster Kubernetes
        uses: Azure/k8s-deploy@v3.1
        with:
          images: hernanisoares/kube-news:${{github.run_number}}
          manifests: ./iac/kube-news/k8s/deployment.yaml
